///
/// Export styles for the types of BOM's generated by this program
/// Author: Justin Morrow
///

namespace JPMorrow.Excel 
{
    // a place for various
    public class ExcelSheetStyle 
    {
        
        public string SheetTitleSuffix { get; private set; }
        public string[] ColumnHeaders { get; private set; }
        public char[] ColumnExtents { get; private set; }
        
        public ExcelSheetStyle(string sheet_title_suffix, string[] headers, char[] extents) 
        {
            ColumnHeaders = headers;
            ColumnExtents = extents;
            SheetTitleSuffix = sheet_title_suffix;
        }
    }

    public static class ExportStyle 
    {
        public static ExcelSheetStyle LegacyP3InWall = new ExcelSheetStyle(
            " - P3 In Wall - M.P.A.C.T. - ",
            new[] { "Part Name", "Qty", "Labor Per Unit", "Labor Code", "Total Labor Hours" },
            new[] { 'A', 'E' }
        );
    }
}
